### ISSUE TITLE
Incorrect @return broke PHPStorm autocomplete

### ISSUE THREAD

**Issue by sc0rp10** [beheh/flaps#3]
In `\BehEh\Flaps\Flaps::getFlap` given incorrect PHPDoc: leading backslash missed and this broke PHPStorm' autocomplete (see attached screenshot). IDE resolves BehEh\Flaps\Flap as nested namespace \BehEh\Flaps\Flaps\BehEh\Flaps\Flap.
If I add backslash in @return autocomplete works fine.

``` php
    /**
     * Creates a new Flap and returns it, setting default violation handler.,
     * @param string $name the name of the flap
     * @return BehEh\Flaps\Flap the created flap here <- here
     */
```

![](https://cdn.weblab.pro/6vjy8.png)

**Comment by beheh** [comment]
Thanks for the report!
